name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22, 1.23]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-test-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-${{ matrix.go-version }}-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run all tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Generate coverage report
        run: go tool cover -html=coverage.txt -o coverage.html

      - name: Verify all tests ran
        run: |
          echo "Verifying test coverage includes all test files..."
          go test -list=Test ./... | grep -E "^(Test|Benchmark)" | wc -l
          echo "Total test functions found above"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          flags: all-tests
          name: codecov-blockchain-health-go${{ matrix.go-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-blockchain-health-go${{ matrix.go-version }}
          path: |
            coverage.txt
            coverage.html
          retention-days: 30

  benchmark:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download

      - name: Run benchmarks
        run: |
          echo "Running performance benchmarks..."
          go test -bench=. -benchmem -run=^$ ./... > benchmark-results.txt || true
          cat benchmark-results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark-results.txt
          retention-days: 30
